### ISSUE TITLE
windows wallet doesnt show block count in corner 

### ISSUE THREAD

**Issue by rekk2** [zixxcrypto/zixxcore#12]
![image](https://user-images.githubusercontent.com/32183761/40493702-400c0c4a-5f41-11e8-907b-02760794a1cb.png)

**Comment by rekk2** [comment]
now it works
![image](https://user-images.githubusercontent.com/32183761/40494284-7b16d5ee-5f42-11e8-96a7-4b9af0daf17a.png)

**Comment by zixxcrypto** [comment]
We will ensure it's visible there and in the other relevant places.

**Comment by zixxcrypto** [comment]
Fixed on the previous release. No longer applicable.
