### ISSUE TITLE
Wallet for MacOS don't start 

### ISSUE THREAD

**Issue by ananda7** [zixxcrypto/zixxcore#14]
Process:               Zixx-Qt [1818]
Path:                  /Applications/Zixx-Qt.app/Contents/MacOS/Zixx-Qt
Identifier:            org.zixx.Zixx-Qt
Version:               0.16.4 (0.16.4)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Zixx-Qt [1818]
User ID:               501

Date/Time:             2018-06-28 13:39:01.667 +0700
OS Version:            Mac OS X 10.13.5 (17F77)
Report Version:        12
Bridge OS Version:     3.0 (14Y664)
Anonymous UUID:        08837EC3-A624-5F33-3183-43DEF5E8A057

Sleep/Wake UUID:       8A0032F1-997D-4DD6-9323-61B5E531C8D8

Time Awake Since Boot: 26000 seconds
Time Since Wake:       2300 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @loader_path/libboost_system-mt.dylib
  Referenced from: /Applications/Zixx-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib
  Reason: image not found

Binary Images:
       0x10fa6e000 -        0x110a0bff7 +org.zixx.Zixx-Qt (0.16.4 - 0.16.4) <35E39110-ED37-32F8-A072-DE3E08A6A84B> /Applications/Zixx-Qt.app/Contents/MacOS/Zixx-Qt
       0x110b56000 -        0x110b58ff7 +libboost_system.dylib (0) <6D4202B3-758D-3014-A208-8577024B9BB3> /Applications/Zixx-Qt.app/Contents/Frameworks/libboost_system.dylib
       0x110b5f000 -        0x110b6eff7 +libboost_filesystem.dylib (0) <BDEC6C74-6778-342E-AFF0-62ABA7D03E43> /Applications/Zixx-Qt.app/Contents/Frameworks/libboost_filesystem.dylib
       0x110b7e000 -        0x110bb0fff +libboost_program_options-mt.dylib (0) <AEDAEFBB-E939-3404-BD07-2313425473FA> /Applications/Zixx-Qt.app/Contents/Frameworks/libboost_program_options-mt.dylib
       0x110bd0000 -        0x110bddfff +libboost_thread-mt.dylib (0) <CE22F73C-D5EA-32D9-A732-D824D54D622C> /Applications/Zixx-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib
       0x110bea000 -        0x110bedff7 +libboost_chrono-mt.dylib (0) <19312DE7-D906-321B-9A48-5822E962A2EB> /Applications/Zixx-Qt.app/Contents/Frameworks/libboost_chrono-mt.dylib
       0x110bf7000 -        0x110cfaff3 +QtNetwork (0) <DD8EF1B7-0C03-386D-AE11-E618BC4C87F3> /Applications/Zixx-Qt.app/Contents/Frameworks/QtNetwork.framework/Versions/5/QtNetwork
       0x110d45000 -        0x111171ff7 +QtWidgets (0) <AD15E490-1C7E-344F-9B40-A684A9160882> /Applications/Zixx-Qt.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
       0x1112d9000 -        0x111706ff7 +QtGui (0) <96CF196B-1BBB-317F-9F39-86DD41787FC9> /Applications/Zixx-Qt.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
       0x111801000 -        0x111ce2fff +QtCore (0) <0967D4C1-9487-3421-9861-304DEE848576> /Applications/Zixx-Qt.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
       0x111d96000 -        0x111df0ff7 +QtDBus (0) <6BFE4F79-D9C9-381E-A68D-BB5E6FFEDF4E> /Applications/Zixx-Qt.app/Contents/Frameworks/QtDBus.framework/Versions/5/QtDBus
       0x111e09000 -        0x111f3bff7 +libprotobuf.15.dylib (0) <7126DB9C-1EE3-36D1-B366-9047D43A8A3C> /Applications/Zixx-Qt.app/Contents/Frameworks/libprotobuf.15.dylib
       0x111ff0000 -        0x112114ff7 +libdb_cxx-4.8.dylib (0) <893E0F96-1F8A-3073-B1CF-CC60610C3E90> /Applications/Zixx-Qt.app/Contents/Frameworks/libdb_cxx-4.8.dylib
       0x11214e000 -        0x11218dfff +libssl.1.0.0.dylib (0) <EBB8B528-77C1-3324-8A1B-08291E30F4D6> /Applications/Zixx-Qt.app/Contents/Frameworks/libssl.1.0.0.dylib
       0x1121b0000 -        0x11231fb47 +libcrypto.1.0.0.dylib (0) <A8D1374C-6F23-326C-B96C-8BAEA73E291D> /Applications/Zixx-Qt.app/Contents/Frameworks/libcrypto.1.0.0.dylib
       0x112387000 -        0x11238fffb +libminiupnpc.17.dylib (0) <C702411D-92DB-3214-B910-B1580AF33F1C> /Applications/Zixx-Qt.app/Contents/Frameworks/libminiupnpc.17.dylib
       0x112398000 -        0x112399fff +libevent_pthreads-2.1.6.dylib (0) <6F618640-46F3-3B56-A22C-26941B4D8790> /Applications/Zixx-Qt.app/Contents/Frameworks/libevent_pthreads-2.1.6.dylib
       0x1123a3000 -        0x1123d0fff +libevent-2.1.6.dylib (0) <891F379E-D5F9-39EB-BECA-2E24F943B7B3> /Applications/Zixx-Qt.app/Contents/Frameworks/libevent-2.1.6.dylib
       0x113caf000 -        0x113cf99df  dyld (551.3) <AFAB4EFA-7020-34B1-BBEF-0F26C6D3CA36> /usr/lib/dyld
    0x7fff423ce000 -     0x7fff4322cfff  com.apple.AppKit (6.9 - 1561.40.112) <2D9940B9-9C9B-3FF1-8E9F-26CD7E7E3B5A> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff4327e000 -     0x7fff4327efff  com.apple.ApplicationServices (48 - 50) <7BD49390-6D89-3429-80CD-6C70334F9B49> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
    0x7fff44df2000 -     0x7fff45293fef  com.apple.CoreFoundation (6.9 - 1452.23) <945E5C0A-86C5-336E-A64F-5BF06E78985A> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff45f6b000 -     0x7fff45f6bfff  com.apple.CoreServices (822.33 - 822.33) <1AC8CE39-003D-3901-909F-2DE6838AF097> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff46f53000 -     0x7fff47319fff  com.apple.Foundation (6.9 - 1452.23) <E64540AD-1755-3C16-8537-552A00E92541> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff6a461000 -     0x7fff6a494ff7  libclosured.dylib (551.3) <DC3DA678-9C40-339C-A9C6-32AB74FCC682> /usr/lib/closure/libclosured.dylib
    0x7fff6a99b000 -     0x7fff6a99cffb  libSystem.B.dylib (1252.50.4) <CDA73F3E-2A7D-3354-818A-580317A03255> /usr/lib/libSystem.B.dylib
    0x7fff6abd0000 -     0x7fff6ac26fff  libc++.1.dylib (400.9) <7D3DACCC-3804-393C-ABC1-1A580FD00CB6> /usr/lib/libc++.1.dylib
    0x7fff6ac27000 -     0x7fff6ac4bff7  libc++abi.dylib (400.8.2) <EF5E37D7-11D9-3530-BE45-B986612D13E2> /usr/lib/libc++abi.dylib
    0x7fff6c053000 -     0x7fff6c4417e7  libobjc.A.dylib (723) <DD9E5EC5-B507-3249-B700-93433E2D5EDF> /usr/lib/libobjc.A.dylib
    0x7fff6cb17000 -     0x7fff6cb1bff7  libcache.dylib (80) <092479CB-1008-3A83-BECF-E115F24D13C1> /usr/lib/system/libcache.dylib
    0x7fff6cb1c000 -     0x7fff6cb26ff3  libcommonCrypto.dylib (60118.50.1) <029F5985-9B6E-3DCB-9B96-FD007678C6A7> /usr/lib/system/libcommonCrypto.dylib
    0x7fff6cb27000 -     0x7fff6cb2efff  libcompiler_rt.dylib (62) <968B8E3F-3681-3230-9D78-BB8732024F6E> /usr/lib/system/libcompiler_rt.dylib
    0x7fff6cb2f000 -     0x7fff6cb38ffb  libcopyfile.dylib (146.50.5) <3885083D-50D8-3EEC-B481-B2E605180D7F> /usr/lib/system/libcopyfile.dylib
    0x7fff6cb39000 -     0x7fff6cbbefff  libcorecrypto.dylib (562.50.17) <67007279-24E1-3F30-802D-A55CD5C27946> /usr/lib/system/libcorecrypto.dylib
    0x7fff6cc46000 -     0x7fff6cc7fff7  libdispatch.dylib (913.60.2) <414353F7-3A9F-3091-AFCE-E66F74687D5D> /usr/lib/system/libdispatch.dylib
    0x7fff6cc80000 -     0x7fff6cc9dff7  libdyld.dylib (551.3) <CF59A5A5-288B-30E6-BD42-9056B4E4139A> /usr/lib/system/libdyld.dylib
    0x7fff6cc9e000 -     0x7fff6cc9effb  libkeymgr.dylib (28) <E34E283E-90FA-3C59-B48E-1277CDB9CDCE> /usr/lib/system/libkeymgr.dylib
    0x7fff6ccac000 -     0x7fff6ccacff7  liblaunch.dylib (1205.60.9) <4B2943A9-0994-3E8B-94B8-98DA9CED0021> /usr/lib/system/liblaunch.dylib
    0x7fff6ccad000 -     0x7fff6ccb1ffb  libmacho.dylib (906) <1902A611-081A-3452-B11E-EBD1B166E831> /usr/lib/system/libmacho.dylib
    0x7fff6ccb2000 -     0x7fff6ccb4ff3  libquarantine.dylib (86) <26C0BA22-8F93-3A07-9A4E-C8D53D2CE42E> /usr/lib/system/libquarantine.dylib
    0x7fff6ccb5000 -     0x7fff6ccb6ff3  libremovefile.dylib (45) <711E18B2-5BBE-3211-A916-56740C27D17A> /usr/lib/system/libremovefile.dylib
    0x7fff6ccb7000 -     0x7fff6cccefff  libsystem_asl.dylib (356.50.1) <3B24F2D1-B578-359D-ADB2-0ED19A364C38> /usr/lib/system/libsystem_asl.dylib
    0x7fff6cccf000 -     0x7fff6cccffff  libsystem_blocks.dylib (67) <17303FDF-0D2D-3963-B05E-B4DF63052D47> /usr/lib/system/libsystem_blocks.dylib
    0x7fff6ccd0000 -     0x7fff6cd59ff7  libsystem_c.dylib (1244.50.9) <1187BFE8-4576-3247-8177-481554E1F9E7> /usr/lib/system/libsystem_c.dylib
    0x7fff6cd5a000 -     0x7fff6cd5dffb  libsystem_configuration.dylib (963.50.8) <DF6B5287-203E-30CB-9947-78DF446C72B8> /usr/lib/system/libsystem_configuration.dylib
    0x7fff6cd5e000 -     0x7fff6cd61ffb  libsystem_coreservices.dylib (51) <486000D3-D8CB-3BE7-8EE5-8BF380DE6DF7> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff6cd62000 -     0x7fff6cd63fff  libsystem_darwin.dylib (1244.50.9) <09C21A4A-9EE0-388B-A9D9-DFF8F6758791> /usr/lib/system/libsystem_darwin.dylib
    0x7fff6cd64000 -     0x7fff6cd6aff7  libsystem_dnssd.dylib (878.50.17) <C12E2075-3E4B-3187-8B3B-F6150FCB82E0> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff6cd6b000 -     0x7fff6cdb4ff7  libsystem_info.dylib (517.30.1) <AB634A98-B8AA-3804-8436-38261FC8EC4D> /usr/lib/system/libsystem_info.dylib
    0x7fff6cdb5000 -     0x7fff6cddbff7  libsystem_kernel.dylib (4570.61.1) <D7F2010A-EA32-3F62-90DE-85E3C5CC3065> /usr/lib/system/libsystem_kernel.dylib
    0x7fff6cddc000 -     0x7fff6ce27fcb  libsystem_m.dylib (3147.50.1) <8CFB51C9-B422-3379-8552-064C63943A23> /usr/lib/system/libsystem_m.dylib
    0x7fff6ce28000 -     0x7fff6ce47fff  libsystem_malloc.dylib (140.50.6) <7FD43735-9DDD-300E-8C4A-F909A74BDF49> /usr/lib/system/libsystem_malloc.dylib
    0x7fff6ce48000 -     0x7fff6cf78ff7  libsystem_network.dylib (1229.60.3) <D17B38B7-BE5D-3A9C-9257-F045E7647E8A> /usr/lib/system/libsystem_network.dylib
    0x7fff6cf79000 -     0x7fff6cf83ffb  libsystem_networkextension.dylib (767.60.1) <1745C91F-9AF0-357D-BD40-34451A2D6A5E> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff6cf84000 -     0x7fff6cf8dff3  libsystem_notify.dylib (172) <08012EC0-2CD2-34BE-BF93-E7F56491299A> /usr/lib/system/libsystem_notify.dylib
    0x7fff6cf8e000 -     0x7fff6cf95ff7  libsystem_platform.dylib (161.50.1) <6355EE2D-5456-3CA8-A227-B96E8F1E2AF8> /usr/lib/system/libsystem_platform.dylib
    0x7fff6cf96000 -     0x7fff6cfa1fff  libsystem_pthread.dylib (301.50.1) <0E51CCBA-91F2-34E1-BF2A-FEEFD3D321E4> /usr/lib/system/libsystem_pthread.dylib
    0x7fff6cfa2000 -     0x7fff6cfa5fff  libsystem_sandbox.dylib (765.60.1) <E5DE4B2F-202D-3474-9F08-7CAB1501D411> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff6cfa6000 -     0x7fff6cfa7ff3  libsystem_secinit.dylib (30) <DE8D14E8-A276-3FF8-AE13-77F7040F33C1> /usr/lib/system/libsystem_secinit.dylib
    0x7fff6cfa8000 -     0x7fff6cfafff7  libsystem_symptoms.dylib (820.60.2) <9C9E82AB-D1EE-3EC7-B20E-44338CE092AC> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff6cfb0000 -     0x7fff6cfc3fff  libsystem_trace.dylib (829.50.17) <6568D68B-1D4C-38EE-90A9-54821D6403C0> /usr/lib/system/libsystem_trace.dylib
    0x7fff6cfc5000 -     0x7fff6cfcaff7  libunwind.dylib (35.3) <BEF3FB49-5604-3B5F-82B5-332B80023AC3> /usr/lib/system/libunwind.dylib
    0x7fff6cfcb000 -     0x7fff6cff8fff  libxpc.dylib (1205.60.9) <16132357-B57A-35F5-B165-487D3F759F45> /usr/lib/system/libxpc.dylib

Model: MacBookPro13,2, BootROM MBP132.0244.B00, 2 processors, Intel Core i5, 2.9 GHz, 16 GB, SMC 2.37f20
Graphics: Intel Iris Graphics 550, Intel Iris Graphics 550, Built-In
Memory Module: BANK 0/DIMM0, 8 GB, LPDDR3, 2133 MHz, 0x802C, 0x4D5435324C31473332443450472D30393320
Memory Module: BANK 1/DIMM0, 8 GB, LPDDR3, 2133 MHz, 0x802C, 0x4D5435324C31473332443450472D30393320
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x157), Broadcom BCM43xx 1.0 (7.77.37.31.1a9)
Bluetooth: Version 6.0.6f2, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi 2, AirPort, en0
USB Device: USB 3.0 Bus
USB Device: USB2.0 Hub
USB Device: USB2.0 Hub
USB Device: USB 2.0 BILLBOARD
USB Device: USB Storage
USB Device: StillImage
USB Device: iBridge
USB Device: USB3.0 Hub
USB Device: USB 10/100/1000 LAN
Thunderbolt Bus: MacBook Pro, Apple Inc., 33.1
Thunderbolt Bus: MacBook Pro, Apple Inc., 33.1

**Comment by zixxcrypto** [comment]
Fixed on the latest release.
