### ISSUE TITLE
Feature request: [Deadthings] : "Can we make confirmed tx's on the overview tab of the wallet appear darker? Right now everything's this light grey and it's driving me batty."

### ISSUE THREAD

**Issue by GerryMcA** [zixxcrypto/zixxcore#7]

**Comment by zixxcrypto** [comment]
Passed on to the design team.

**Comment by deadthings** [comment]
It's true. I did say that. Sorry for the silliness, but you know, when in Rome (Discord)...

**Comment by zixxcrypto** [comment]
We don't want people getting insane because of UI. There are _far_ better reasons to detach yourself from reality.

**Comment by zixxcrypto** [comment]
Changed the hue of the transaction text.
