### ISSUE TITLE
"reward address" is visible in masternode.conf

### ISSUE THREAD

**Issue by GerryMcA** [zixxcrypto/zixxcore#9]

**Comment by GerryMcA** [comment]
In the masternode.conf file the words "reward address" are seen in the example text. This remains even if the file is deleted and regenerated by the wallet on restart.
![image](https://user-images.githubusercontent.com/37547396/39973256-a3f5c0fe-5715-11e8-9422-fd9fc6b9ebab.png)

**Comment by zixxcrypto** [comment]
Removed.
